sudo: false
dist: trusty
language: c

env:
  global:
    - PROTOBUF_VERSION=3.4.0
    - TOOLCHAIN_SHORTVER=7-2018q2
    - TOOLCHAIN_LONGVER=gcc-arm-none-eabi-7-2018-q2-update
  matrix:
    - GOAL=stm32
    - GOAL=unix
    - GOAL=src

matrix:
  include:
    - compiler: clang
      env: GOAL=unix

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - build-essential
    - gcc-multilib
    - libusb-1.0-0-dev
    - libudev-dev
    - python3.6
    - python3.6-dev
    - python3.6-venv

cache:
  directories:
    - $HOME/libsodium

before_install:
    - python3.6 -m ensurepip --user
    - python3.6 -m pip install --user pipenv

install:
    - curl -LO "https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip"
    - unzip "protoc-${PROTOBUF_VERSION}-linux-x86_64.zip" -d protoc
    - export PATH="$(pwd)/protoc/bin:$PATH"
    - ./travis-install-libsodium.sh
    - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
    - pipenv run pip install pip==18.0
    - pipenv install

before_script:
    - test "$GOAL" != "stm32" || wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/$TOOLCHAIN_SHORTVER/$TOOLCHAIN_LONGVER-linux.tar.bz2
    - test "$GOAL" != "stm32" || tar xfj $TOOLCHAIN_LONGVER-linux.tar.bz2
    - test "$GOAL" != "stm32" || export PATH=$PWD/$TOOLCHAIN_LONGVER/bin:$PATH

script:
  - test "$GOAL" != "src" || pipenv run make style
  - test "$GOAL" != "src" || pipenv run make templates_check

  - test "$GOAL" != "stm32" || pipenv run make build_cross
  - test "$GOAL" != "stm32" || pipenv run make build_boardloader
  - test "$GOAL" != "stm32" || pipenv run make build_bootloader
  - test "$GOAL" != "stm32" || pipenv run make build_prodtest
  - test "$GOAL" != "stm32" || pipenv run make build_firmware
  - test "$GOAL" != "stm32" || test "$TREZOR_MODEL" = "1" || pipenv run make sizecheck

  - test "$GOAL" != "unix" || pipenv run make build_unix_noui
  - test "$GOAL" != "unix" || pipenv run make test
  - test "$GOAL" != "unix" || test "$TREZOR_MODEL" = "1" || pipenv run make test_emu
  - test "$GOAL" != "unix" || test "$TREZOR_MODEL" = "1" || pipenv run make test_emu_monero

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
